Add an optional map descriptors option for mappings
Kotlin-Discord/kord-extensions pull request #118
Opened 2021-12-03 16:47 UTC by sschr15

this time with an up-to-date upstream

2021-12-04 11:29 UTC, gdude2002 requested changes

2021-12-04 11:29 UTC, gdude2002 commented on extra-modules/extra-mappings/src/main/kotlin/com/kotlindiscord/kord/extensions/modules/extra/mappings/arguments/MappingArguments.kt
> +        "mapDescriptors",
This is user-facing, it shouldn't use programmer casing. `kebab-case` is standard.

2021-12-04 11:29 UTC, gdude2002 commented on extra-modules/extra-mappings/src/main/kotlin/com/kotlindiscord/kord/extensions/modules/extra/mappings/arguments/MCPArguments.kt
> +    override val mapDescriptors = true
Where's this used? We should document which mappings commands don't support supplying this, and set up the commands for them to not take this argument.

2022-01-18 14:20 UTC, sschr15 commented
Better version and update was pulled in #127

2022-01-18 14:20 UTC, closed without merging