mongo adapter: Allow reading of old INT64 Snowflake from databases
Kotlin-Discord/kord-extensions pull request #238
Opened 2023-09-14 16:38 UTC by NoComment1105

Without this, any Snowflake entry in a database record that was created using KMongo, which serialized Snowflakes as INT64, will throw an error. This allows proper decoding of those INT64 entries, alongside the STRING entries

2023-09-15 08:21 UTC, gdude2002 requested changes
Doesn't build - presumably a missing import?

2023-09-15 12:14 UTC, NoComment1105 commented
Whoops, will fix later

2023-09-16 20:16 UTC, gdude2002 approved these changes

2023-09-16 21:08 UTC, merged

2023-09-16 21:08 UTC, gdude2002 commented
Cheers